import type { ColorName } from "../../types.ts";

const bgColor = "background-color:";

export const cssBg: Record<ColorName, string> = {
  black: `${bgColor} #282a36`,
  red: `${bgColor} #ff5555`,
  green: `${bgColor} #50fa7b`,
  yellow: `${bgColor} #f1fa8c`,
  blue: `${bgColor} #6272a4`,
  magenta: `${bgColor} #ff79c6`,
  cyan: `${bgColor} #8be9fd`,
  white: `${bgColor} #f8f8f2`,
  gray: `${bgColor} #44475a`,
  orange: `${bgColor} #ffb86c`,
  pink: `${bgColor} #ff79c6`,
  lime: `${bgColor} #50fa7b`,
  indigo: `${bgColor} #6272a4`,
  violet: `${bgColor} #bd93f9`,
  teal: `${bgColor} #8be9fd`,
  rose: `${bgColor} #ff5555`,
  amber: `${bgColor} #ffb86c`,
  emerald: `${bgColor} #50fa7b`,
  sky: `${bgColor} #8be9fd`,
  purple: `${bgColor} #bd93f9`,
  brown: `${bgColor} #ffb86c`,
  gold: `${bgColor} #f1fa8c`,
  silver: `${bgColor} #f8f8f2`,
  navy: `${bgColor} #6272a4`,
  olive: `${bgColor} #50fa7b`,
  maroon: `${bgColor} #ff5555`,
  aqua: `${bgColor} #8be9fd`,
  turquoise: `${bgColor} #8be9fd`,
  mint: `${bgColor} #50fa7b`,
  coral: `${bgColor} #ff5555`,
  salmon: `${bgColor} #ff5555`,
  crimson: `${bgColor} #ff5555`,
  lavender: `${bgColor} #bd93f9`,
  plum: `${bgColor} #bd93f9`,
  orchid: `${bgColor} #ff79c6`,
  beige: `${bgColor} #f8f8f2`,
  khaki: `${bgColor} #f1fa8c`,
  tan: `${bgColor} #ffb86c`,
  slate: `${bgColor} #44475a`,
  charcoal: `${bgColor} #282a36`,
  steel: `${bgColor} #f8f8f2`,
};
