import type { ColorName } from "../../types.ts";

const color = "color:";

export const cssFg: Record<ColorName, string> = {
  black: `${color} #000`,
  red: `${color} #ff5555`,
  green: `${color} #50fa7b`,
  yellow: `${color} #f1fa8c`,
  blue: `${color} #6272a4`,
  magenta: `${color} #ff79c6`,
  cyan: `${color} #8be9fd`,
  white: `${color} #f8f8f2`,
  gray: `${color} #6272a4`,
  orange: `${color} #ffb86c`,
  pink: `${color} #ff79c6`,
  lime: `${color} #50fa7b`,
  indigo: `${color} #6272a4`,
  violet: `${color} #bd93f9`,
  teal: `${color} #8be9fd`,
  rose: `${color} #ff5555`,
  amber: `${color} #ffb86c`,
  emerald: `${color} #50fa7b`,
  sky: `${color} #8be9fd`,
  purple: `${color} #bd93f9`,
  brown: `${color} #ffb86c`,
  gold: `${color} #f1fa8c`,
  silver: `${color} #f8f8f2`,
  navy: `${color} #6272a4`,
  olive: `${color} #50fa7b`,
  maroon: `${color} #ff5555`,
  aqua: `${color} #8be9fd`,
  turquoise: `${color} #8be9fd`,
  mint: `${color} #50fa7b`,
  coral: `${color} #ff5555`,
  salmon: `${color} #ff5555`,
  crimson: `${color} #ff5555`,
  lavender: `${color} #bd93f9`,
  plum: `${color} #bd93f9`,
  orchid: `${color} #ff79c6`,
  beige: `${color} #f8f8f2`,
  khaki: `${color} #f1fa8c`,
  tan: `${color} #ffb86c`,
  slate: `${color} #6272a4`,
  charcoal: `${color} #44475a`,
  steel: `${color} #f8f8f2`,
};
