import type { BasicBgPalette } from "../../types/index.ts";
import esc from "../escape.ts";

export const basicBg: BasicBgPalette = {
  black: `${esc}[40m`,
  red: `${esc}[41m`,
  green: `${esc}[42m`,
  yellow: `${esc}[43m`,
  blue: `${esc}[44m`,
  magenta: `${esc}[45m`,
  cyan: `${esc}[46m`,
  white: `${esc}[47m`,
  gray: `${esc}[100m`,
  orange: `${esc}[43m`,
  pink: `${esc}[45m`,
  lime: `${esc}[42m`,
  indigo: `${esc}[44m`,
  violet: `${esc}[45m`,
  teal: `${esc}[46m`,
  rose: `${esc}[45m`,
  amber: `${esc}[43m`,
  emerald: `${esc}[42m`,
  sky: `${esc}[46m`,
  purple: `${esc}[45m`,
  brown: `${esc}[43m`,
  gold: `${esc}[43m`,
  silver: `${esc}[47m`,
  navy: `${esc}[44m`,
  olive: `${esc}[43m`,
  maroon: `${esc}[41m`,
  aqua: `${esc}[46m`,
  turquoise: `${esc}[46m`,
  mint: `${esc}[42m`,
  coral: `${esc}[41m`,
  salmon: `${esc}[41m`,
  crimson: `${esc}[41m`,
  lavender: `${esc}[45m`,
  plum: `${esc}[45m`,
  orchid: `${esc}[45m`,
  beige: `${esc}[47m`,
  khaki: `${esc}[43m`,
  tan: `${esc}[43m`,
  slate: `${esc}[100m`,
  charcoal: `${esc}[100m`,
  steel: `${esc}[47m`,

  brightBackground: {
    black: `${esc}[100m`,
    red: `${esc}[101m`,
    green: `${esc}[102m`,
    yellow: `${esc}[103m`,
    blue: `${esc}[104m`,
    magenta: `${esc}[105m`,
    cyan: `${esc}[106m`,
    white: `${esc}[107m`,
  },
};
