import type { Palette } from "../../types/index.ts";
import esc from "../escape.ts";

export const basic: Palette = {
  black: `${esc}[30m`,
  red: `${esc}[31m`,
  green: `${esc}[32m`,
  yellow: `${esc}[33m`,
  blue: `${esc}[34m`,
  magenta: `${esc}[35m`,
  cyan: `${esc}[36m`,
  white: `${esc}[37m`,
  gray: `${esc}[90m`,
  orange: `${esc}[33m`,
  pink: `${esc}[35m`,
  lime: `${esc}[32m`,
  indigo: `${esc}[34m`,
  violet: `${esc}[35m`,
  teal: `${esc}[36m`,
  rose: `${esc}[35m`,
  amber: `${esc}[33m`,
  emerald: `${esc}[32m`,
  sky: `${esc}[36m`,
  purple: `${esc}[35m`,
  brown: `${esc}[33m`,
  gold: `${esc}[33m`,
  silver: `${esc}[37m`,
  navy: `${esc}[34m`,
  olive: `${esc}[33m`,
  maroon: `${esc}[31m`,
  aqua: `${esc}[36m`,
  turquoise: `${esc}[36m`,
  mint: `${esc}[32m`,
  coral: `${esc}[31m`,
  salmon: `${esc}[31m`,
  crimson: `${esc}[31m`,
  lavender: `${esc}[35m`,
  plum: `${esc}[35m`,
  orchid: `${esc}[35m`,
  beige: `${esc}[37m`,
  khaki: `${esc}[33m`,
  tan: `${esc}[33m`,
  slate: `${esc}[90m`,
  charcoal: `${esc}[90m`,
  steel: `${esc}[37m`,
};
