import type { BasicAlias, ColorName } from "../types/index.ts";

export const COLOR_HEX: Record<ColorName, string> = {
  black: "#000000",
  red: "#ff5555",
  green: "#50fa7b",
  yellow: "#f1fa8c",
  blue: "#7aa2f7",
  magenta: "#ff79c6",
  cyan: "#8be9fd",
  white: "#f8f8f2",

  gray: "#9aa5ce",
  orange: "#ff9e64",
  pink: "#f7768e",
  lime: "#9ece6a",
  indigo: "#6366f1",
  violet: "#bb9af7",
  teal: "#2dd4bf",
  rose: "#ff5c8a",
  amber: "#f59e0b",
  emerald: "#10b981",
  sky: "#38bdf8",
  purple: "#a855f7",
  brown: "#a16207",
  gold: "#ffd700",
  silver: "#c0c0c0",
  navy: "#1e3a8a",
  olive: "#808000",
  maroon: "#800000",
  aqua: "#00ffff",
  turquoise: "#40e0d0",
  mint: "#98fb98",
  coral: "#ff7f50",
  salmon: "#fa8072",
  crimson: "#dc143c",
  lavender: "#e6e6fa",
  plum: "#dda0dd",
  orchid: "#da70d6",
  beige: "#f5f5dc",
  khaki: "#f0e68c",
  tan: "#d2b48c",
  slate: "#708090",
  charcoal: "#36454f",
  steel: "#4682b4",
};

// The 16 real terminal colors (8 normal + 8 bright). Every name maps to one
// of them; extended names alias to the closest.
export const BASIC_ALIAS: Record<ColorName, BasicAlias> = {
  black: { base: "black" },
  red: { base: "red" },
  green: { base: "green" },
  yellow: { base: "yellow" },
  blue: { base: "blue" },
  magenta: { base: "magenta" },
  cyan: { base: "cyan" },
  white: { base: "white" },

  gray: { base: "black", bright: true },
  orange: { base: "red", bright: true },
  pink: { base: "magenta", bright: true },
  lime: { base: "green", bright: true },
  indigo: { base: "blue", bright: true },
  violet: { base: "magenta", bright: true },
  teal: { base: "cyan", bright: true },
  rose: { base: "red", bright: true },
  amber: { base: "yellow", bright: true },
  emerald: { base: "green", bright: true },
  sky: { base: "cyan", bright: true },
  purple: { base: "magenta", bright: true },
  brown: { base: "yellow" },
  gold: { base: "yellow", bright: true },
  silver: { base: "black", bright: true },
  navy: { base: "blue" },
  olive: { base: "yellow" },
  maroon: { base: "red" },
  aqua: { base: "cyan" },
  turquoise: { base: "cyan", bright: true },
  mint: { base: "green", bright: true },
  coral: { base: "red", bright: true },
  salmon: { base: "red", bright: true },
  crimson: { base: "red" },
  lavender: { base: "magenta", bright: true },
  plum: { base: "magenta" },
  orchid: { base: "magenta", bright: true },
  beige: { base: "white" },
  khaki: { base: "yellow" },
  tan: { base: "yellow", bright: true },
  slate: { base: "black", bright: true },
  charcoal: { base: "black" },
  steel: { base: "blue", bright: true },
};
